### ISSUE TITLE
Systemd not running --> Builds but fails at Ansible Provisioner

### ISSUE THREAD

**Issue by cortlandx** [solo-io/packer-builder-arm-image#88]
I am trying to build and provision kalipi on a new Pi4 (64-bit).  My kalipi.json file associated .yml, hosts, and sources.list file are inserted below.  

I am getting the following error (at the ansible provisioner step) after running the `sudo packer build kalipi.json` command: 
``` 
kalipi: PLAYBOOK: kalipi.yml ***********************************************************
    kalipi: Positional arguments: /tmp/packer-provisioner-ansible-local/5f80990d-fd11-c94d-f631-db6d07a74beb/kalipi.yml
    kalipi: verbosity: 4
    kalipi: connection: local
    kalipi: timeout: 10
    kalipi: become_method: sudo
    kalipi: tags: ('all',)
    kalipi: inventory: ('/tmp/packer-provisioner-ansible-local/5f80990d-fd11-c94d-f631-db6d07a74beb/Hosts',)
    kalipi: extra_vars: ('packer_build_name=kalipi packer_builder_type=arm-image packer_http_addr=%!s(<nil>) -o IdentitiesOnly=yes', 'ansible_python_interpreter=/usr/bin/python3')
    kalipi: forks: 5
    kalipi: 3 plays in /tmp/packer-provisioner-ansible-local/5f80990d-fd11-c94d-f631-db6d07a74beb/kalipi.yml
    kalipi:
    kalipi: PLAY [Play-#1 for building KaliPi4] ********************************************
    kalipi:
    kalipi: TASK [Gathering Facts] *********************************************************
    kalipi: task path: /tmp/packer-provisioner-ansible-local/5f80990d-fd11-c94d-f631-db6d07a74beb/kalipi.yml:2
    kalipi: <127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
    kalipi: <127.0.0.1> EXEC /bin/sh -c 'echo ~root && sleep 0'
    kalipi: <127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp `"&& mkdir "` echo /root/.ansible/tmp/ansible-tmp-1602263718.512681-23635-149944798217200 `" && echo ansible-tmp-1602263718.512681-23635-149944798217200="` echo /root/.ansible/tmp/ansible-tmp-1602263718.512681-23635-149944798217200 `" ) && sleep 0'
    kalipi: Using module file /usr/lib/python3/dist-packages/ansible/modules/system/setup.py
    kalipi: <127.0.0.1> PUT /root/.ansible/tmp/ansible-local-23622jewsqgll/tmpnmdnc66q TO /root/.ansible/tmp/ansible-tmp-1602263718.512681-23635-149944798217200/AnsiballZ_setup.py
    kalipi: <127.0.0.1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1602263718.512681-23635-149944798217200/ /root/.ansible/tmp/ansible-tmp-1602263718.512681-23635-149944798217200/AnsiballZ_setup.py && sleep 0'
    kalipi: <127.0.0.1> EXEC /bin/sh -c '/usr/bin/python3 /root/.ansible/tmp/ansible-tmp-1602263718.512681-23635-149944798217200/AnsiballZ_setup.py && sleep 0'
    kalipi: <127.0.0.1> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1602263718.512681-23635-149944798217200/ > /dev/null 2>&1 && sleep 0'
    kalipi: ok: [pwned1]
    kalipi: META: ran handlers
    kalipi:
    kalipi: TASK [Update Hostname] *********************************************************
    kalipi: task path: /tmp/packer-provisioner-ansible-local/5f80990d-fd11-c94d-f631-db6d07a74beb/kalipi.yml:7
    kalipi: <127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
    kalipi: <127.0.0.1> EXEC /bin/sh -c 'echo ~root && sleep 0'
    kalipi: <127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp `"&& mkdir "` echo /root/.ansible/tmp/ansible-tmp-1602263737.0431828-23783-178020833826439 `" && echo ansible-tmp-1602263737.0431828-23783-178020833826439="` echo /root/.ansible/tmp/ansible-tmp-1602263737.0431828-23783-178020833826439 `" ) && sleep 0'
    kalipi: Using module file /usr/lib/python3/dist-packages/ansible/modules/system/hostname.py
    kalipi: <127.0.0.1> PUT /root/.ansible/tmp/ansible-local-23622jewsqgll/tmp7rxnydzq TO /root/.ansible/tmp/ansible-tmp-1602263737.0431828-23783-178020833826439/AnsiballZ_hostname.py
    kalipi: <127.0.0.1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1602263737.0431828-23783-178020833826439/ /root/.ansible/tmp/ansible-tmp-1602263737.0431828-23783-178020833826439/AnsiballZ_hostname.py && sleep 0'
    kalipi: <127.0.0.1> EXEC /bin/sh -c '/usr/bin/python3 /root/.ansible/tmp/ansible-tmp-1602263737.0431828-23783-178020833826439/AnsiballZ_hostname.py && sleep 0'
    kalipi: <127.0.0.1> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1602263737.0431828-23783-178020833826439/ > /dev/null 2>&1 && sleep 0'
    kalipi: fatal: [pwned1]: FAILED! => {
    kalipi:     "changed": false,
    kalipi:     "invocation": {
    kalipi:         "module_args": {
    kalipi:             "name": "pwned",
    kalipi:             "use": null
    kalipi:         }
    kalipi:     },
    kalipi:     "msg": "Command failed rc=1, out=, err=\u001b[0;1;31mSystem has not been booted with systemd as init system (PID 1). Can't operate.\u001b[0m\n\u001b[0;1;31mFailed to create bus connection: Host is down\u001b[0m\n"
    kalipi: }
    kalipi:
    kalipi: PLAY RECAP *********************************************************************
    kalipi: pwned1                     : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
    kalipi:
==> kalipi: fuser -k /tmp/742371882
Build 'kalipi' errored after 7 minutes 15 seconds: Error executing Ansible: Non-zero exit status: 2

```

any thoughts on what my issue maybe is of great assistance.  Of note, it builds and provisions fine with shell commands, but inclusion of the ansible provisioner causes issue.

kalipi.json----------------
```
{
    "variables": {},
    "builders": [
        {
            "name": "kalipi",
            "type": "arm-image",
            "iso_url": "https://images.kali.org/arm-images/kali-linux-2020.3a-rpi3-nexmon-64.img.xz",
            "iso_checksum": "56486ff1da0ec5d76b1136863bda079e7d590b9016b5f889b23c443ff4d518de",
            "iso_checksum_type": "sha256",
            "qemu_binary": "qemu-aarch64-static"
        }
    ],
    "provisioners": [
        {
            "type": "shell",
            "inline": [
                "echo nameserver 8.8.8.8 > /etc/resolv.conf"
            ]
        },
        {
            "type": "file",
            "source": "sources.list",
            "destination": "/etc/apt/sources.list"
        },
        {
            "type": "shell",
            "inline": [
                "apt-get -y update",
                "apt-get install -y ansible"
            ]
        },
        {
            "type": "ansible-local",
            "playbook_file": "./Ansible/kalipi.yml",
            "inventory_file": "./Ansible/Hosts",
            "extra_arguments": [
                "--extra-vars \"ansible_python_interpreter=/usr/bin/python3\" -vvvv"
            ]
        }
    ]
}
```
kalipi.yml----
```
---
-   name: "Play-#1 for building KaliPi4"
    hosts: pwned1
    become: yes

    tasks:
        -   name: "Update Hostname"
            hostname:
                name: "{{ new_hostname }}"

        -   name: "Add hostname to /etc/hosts"
            lineinfile:
                dest: /etc/hosts
                regexp: '^127\.0\.0\.1[ \t]+localhost'
                line: "127.0.0.1 localhost {{ new_hostname }}"
                state: present

        -   name: "Add the group 'pwned' with a specific gid"
            group:
                name: pwned
                state: present
                gid: 2002

        -   name: "Add the user 'pwned' with a specific uid and primary group of 'pwned'"
            user:
                name: pwned
                uid: 2002
                group: pwned
                password: $6$PQHzHnLXqt/S6nR$RvtYap2ZgQKn1bIyppPBVy7Hurpdb44QBFHCw59gPACyLsCVg61A6T665/nWP1OhrHC9yWfMbwgJaXfcG2Y9c0
                generate_ssh_key: yes
                ssh_key_bits: 2048
                ssh_key_file: .ssh/id_rsa
                state: present
                shell: /bin/bash

        -   name: "Add user 'pwned' to sudo"
            lineinfile:
                path: /etc/sudoers.d/pwned
                line: "valant ALL=(ALL) NOPASSWD: ALL"
                mode: 0440
                create: yes
                validate: "visudo -cf %s"

-   name: "Play-#2 for removing default kali profiles"
    hosts: pwned2
    become: yes

    tasks:
        -   name: "Remove default user 'kali'"
            user:
                name: kali
                state: absent
                remove: yes
                force: yes

        -   name: "Remove default group 'kali'"
            group:
                name: kali
                state: absent

-   name: "Play-#3 to update apt and install packages"
    hosts: pwned2
    become: yes
    vars:
        packages:
            apt:
                hold:
                remove:
                    - xfce4
                    - xfce4-places-plugin
                    - xfce-goodies
                    - lightdm

                install:
                    - bettercap
                    - mdk4

    tasks:

        -   name: "Remove preconfigured repository from source list"
            apt_repository:
                repo: deb http://kali.download/kali http://http.kali.org/kali main contrib non-free
                state: absent
                install_python_apt: true

        -   name: "Add kali rolling repository to source list"
            apt_repository:
                repo: deb http://http.kali.org/kali kali-rolling main non-free contrib
                state: present

        -   name: "Update and Upgrade apt package"
            apt:
                update_cache: yes
                upgrade: yes
                force_apt_get: yes
            async: 3600
            poll: 30
            register: apt_sleeper

        -   name: "Install packages"
            apt:
                name: "{{ packages.apt.install }}"
                state: latest
            async: 3600
            poll: 30
            register: apt_sleeper

        -   name: "Remove Kali Desktop package"
            apt:
                name: "{{ packages.apt.remove }}"
                state: absent
                autoclean: yes
                autoremove: yes
                update_cache: yes
                purge: yes
                force_apt_get: yes
            async: 3600
            poll: 30
            register: apt_sleeper

        -   name: "Reboot pi post-configuration"
            reboot:
```
host (inventory file)-----
```
[kalipi]
pwned1 ansible_host=127.0.0.1 ansible_user=kali ansible_ssh_pass=kali ansible_become_pass=kali ansible_python_interpreter=/usr/bin/python3 new_hostname=pwned
pwned2 ansible_host=127.0.0.1 ansible_user=pwned ansible_ssh_pass=pwned ansible_become_pass=pwned ansible_python_interpreter=/usr/bin/python3
```
sources.list file
```
deb http://http.kali.org/kali kali-rolling main contrib non-free
# For source package access, uncomment the following line
# deb-src http://http.kali.org/kali kali-rolling main contrib non-free
```
